version: "3.3"
services:
  db:
    container_name: bzdb
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: bzapp
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
      DJANGO_MANAGEPY_MIGRATE: "on"
      ENGINE: 'django.db.backends.postgresql'
      NAME: 'postgres'
      USER: 'postgres'
      PASSWORD: 'postgres'
      HOST: 'db'
      PORT: 5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db